### ISSUE TITLE
Preventing form submission after calling `validate`

### ISSUE THREAD

**Issue by ajhurliman** [thihathit/react-joi#2]
Thanks for building this project, the React integration is great! One issue that I've been running into is preventing form submission after calling `validate` though. For instance, using the sample code on https://www.npmjs.com/package/react-joi if I were to change the button click's actions to something like the following then by the time I try to call `someApiCall` the state has not updated and I'm unable to tell whether the required fields have actually been filled out or not.

I can get around it by manually checking if `state.$data.name === ''` but that seems to defeat the purpose of the library.

I've seen other uses of Joi where `validate` returns the values which would solve my problem, but it doesn't look like it returns anything here. Am I on the wrong track? 

```
const handleSubmit = () => {
  validate()
  if (state.$all_errors.length > 0) return
  someApiCall(state.$data)
}
...
return (
   ...
  <button onClick={validate}>Submit</button>
)
```
  
Thanks again for the code!

**Comment by thihathit** [comment]
You might want to capture `$validation_success` or `$invalid` from validation state for this purpose.

Note: Callback features like onSuccess/onError are not supported yet. So you'll need to capture the success state with `useEffect`.

So.. it should be something like this:

```jsx
//const handleSubmit = () => {
//  validate()
//  if (state.$all_errors.length > 0) return
//  someApiCall(state.$data)
//}

// Because "state" is internally React.useState
// This is the only way to capture them as of now
useEffect(() => {
  if(state.$validation_success) {
    someApiCall(state.$data)
  }
}, [state])
...
return (
   ...
  <button onClick={validate}>Submit</button>
)
```
