### ISSUE TITLE
Support for React 18

### ISSUE THREAD

**Issue by rogueturnip** [thihathit/react-joi#8]
I was wondering if there is a technical issue the package is set to React 17?

Thanks!

**Comment by thihathit** [comment]
no, it's just peerDependency, it'll use your project's react. let me know if it doesn't.

**Comment by rogueturnip** [comment]
Any chance you'll be doing a patch release with the peerDependency updated?  Right now the npm fails to install when using npm.

**Comment by thihathit** [comment]
sure, maybe i'll remove it if i could

**Comment by thihathit** [comment]
can you show me error/log message if you could?

**Comment by rogueturnip** [comment]
sure! 
![image](https://user-images.githubusercontent.com/7782364/203816531-53826df8-adb4-4047-90bf-3f9d46c9a554.png)

**Comment by rogueturnip** [comment]
I just wanted to mention.  I switched to using yarn and it installs.  the blocking is an issue for anyone using npm.

**Comment by thihathit** [comment]
should work with `v1.3.0`.
